# Generated by Django 4.1.6 on 2023-02-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="name of company"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="description of company"),
                ),
                ("location", models.CharField(max_length=120, verbose_name="location")),
            ],
        ),
    ]
